name: Deploy
on:
  push:
  workflow_dispatch:
  repository_dispatch:
    types: [redeploy]
jobs:
  build:
    runs-on: ubuntu-latest
    name: Build
    steps:
      # - name: trigger vercel deploy
      #   if: github.event_name=='repository_dispatch' || github.event_name=='workflow_dispatch'
      #   run: curl ${{ secrets.VERCEL_HOOK }}
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Get yarn cache directory
        id: yarn-cache-dir
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - name: Yarn cache
        uses: actions/cache@v2
        with:
          path: ${{ steps.yarn-cache-dir.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Yarn install
        run: "yarn --pure-lockfile"
      - name: Build
        run: yarn build
      # - name: Deploy to surge
      #   uses: dswistowski/surge-sh-action@v1
      #   with:
      #     domain: "blog.owenyoung.com"
      #     project: "./public"
      #     login: ${{ secrets.SURGE_LOGIN }}
      #     token: ${{ secrets.SURGE_TOKEN }}
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          user_name: "github-actions[bot]"
          user_email: "github-actions[bot]@users.noreply.github.com"
