name: Deploy
on:
  push:
  workflow_dispatch:
  repository_dispatch:
    types: [redeploy]
jobs:
  build:
    runs-on: ubuntu-latest
    name: Build
    steps:
      # - name: trigger vercel deploy
      #   if: github.event_name=='repository_dispatch' || github.event_name=='workflow_dispatch'
      #   run: curl ${{ secrets.VERCEL_HOOK }}
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Setup | Node
        uses: actions/setup-node@v2
        with:
          node-version: "16"
      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - name: Install dependencies
        run: npm i
      - name: Build Site
        run: npm run build
      # - name: Deploy to surge
      #   uses: dswistowski/surge-sh-action@v1
      #   with:
      #     domain: "blog.owenyoung.com"
      #     project: "./public"
      #     login: ${{ secrets.SURGE_LOGIN }}
      #     token: ${{ secrets.SURGE_TOKEN }}
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          user_name: "github-actions[bot]"
          user_email: "github-actions[bot]@users.noreply.github.com"
